development:
  adapter: postgresql
  encoding: unicode
  database: tourbot_development
  pool: 5
  username: postgres
  password: 

test: &test
  adapter: postgresql
  encoding: unicode
  database: tourbot_test
  pool: 5
  username: postgres
  password: 

cucumber:
  <<: *test
